name: Update m3u8 Link

on:
  schedule:
    - cron: "*/10 * * * *"  # hÉ™r 10 dÉ™qiqÉ™dÉ™ bir
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Repo klonla
        uses: actions/checkout@v3
      - name: Python qur
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: AsÄ±lÄ±lÄ±qlarÄ± quraÅŸdÄ±r
        run: pip install yt-dlp
      - name: Linki Ã§Ä±xart
        run: python extract_m3u8.py
      - name: Yadda saxla
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ğŸ” Link yenilÉ™ndi"
