name: Update m3u8 Link (NOWTV)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonla
        uses: actions/checkout@v3

      - name: Python qur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: LazÄ±mi paketlÉ™ri qur
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-driver chromium-browser

      - name: Skripti iÅŸÉ™ sal
        run: python extract_m3u8.py

      - name: FayllarÄ± Git-É™ yaz
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ğŸ” NOWTV link yenilÉ™ndi"
